{
 "title": "Kafka: Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "prom_kafka_job",
    "label": "Job",
    "query": {
     "query": "label_values(kafka_cluster_partition_insyncreplicascount{}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Общая статистика",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Число брокеров",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_kafkaserver_brokerstate{})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Число топиков",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kafka_cluster_partition_replicascount{}) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Число партиций",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kafka_cluster_partition_replicascount{}) by (topic, partition))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Реплицированных партиций",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_replicascount{}) - sum(kafka_cluster_partition_underreplicated{})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Нереплицированных партиций",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underreplicated{})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Недоступных партиций",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Активных контроллеров",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Консумер-группы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Число групп потребителей",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kafka_consumergroup_current_offset{}) by (consumergroup) > 0)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Отставание оффсета, p95",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.95, sum(kafka_consumergroup_lag{}) by (consumergroup, topic))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сообщений (в секунду)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_messagesin_total{}[5m])) / 5 / 60",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Входящий трафик (в секунду)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_bytesin_total{}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Исходящий трафик (в секунду)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_bytesout_total{}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Производительность", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Общее время отклика API, p99",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.99, (rate(kafka_network_requestmetrics_totaltimems{quantile=\"0.99\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время отклика Fetch API, p99",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.99, (rate(kafka_network_requestmetrics_totaltimems{quantile=\"0.99\",request=\"Fetch\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время отклика OffsetCommit API, p99",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.99, (rate(kafka_network_requestmetrics_totaltimems{quantile=\"0.99\",request=\"OffsetCommit\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время отклика Produce API, p99",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.99, (rate(kafka_network_requestmetrics_totaltimems{quantile=\"0.99\",request=\"Produce\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Число ожидающих операций",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_delayedoperationpurgatory_purgatorysize{})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}