{
 "title": "Kafka: Performance",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_cluster_partition_insyncreplicascount, instance)"
    }
   },
   {
    "name": "request",
    "label": "API request",
    "query": {
     "query": "label_values(kafka_network_requestmetrics_responsesendtimems, request)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Время ответа API-вызовов (RequestMetrics)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile(0.99, (rate(kafka_network_requestmetrics_totaltimems{quantile=\"0.50\",instance=~\"$instance\",request=~\"$request\"}[$__rate_interval])))",
     "legendFormat": "mean"
    },
    {
     "expr": "quantile(0.99, (rate(kafka_network_requestmetrics_totaltimems{quantile=\"0.95\",instance=~\"$instance\",request=~\"$request\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile(0.99, (rate(kafka_network_requestmetrics_totaltimems{quantile=\"0.99\",instance=~\"$instance\",request=~\"$request\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Объём трафика по API-вызовам (RequestMetrics)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kafka_network_requestmetrics_requestbytes{instance=~\"$instance\",request=~\"$request\"}) > 0",
     "legendFormat": "traffic"
    }
   ]
  },
  {
   "title": "Число API-вызовов (RequestMetrics)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requests_total{instance=~\"$instance\",request=~\"$request\"}[$__interval]))",
     "legendFormat": "Processed requests "
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_errors_total{instance=~\"$instance\",request=~\"$request\",error!=\"NONE\"}[$__interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Число ожидающих операций (PurgatorySize)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_delayedoperationpurgatory_purgatorysize{delayedOperation=~\"$request\",instance=~\"$instance\"}) by (delayedOperation)",
     "legendFormat": "{{ delayedOperation }}"
    }
   ]
  },
  {
   "title": "Размер очереди на чтение и запись (RequestChannel)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_network_requestchannel_requestqueuesize{instance=~\"$instance\"})",
     "legendFormat": "Request queue size"
    },
    {
     "expr": "sum(kafka_network_requestchannel_responsequeuesize{instance=~\"$instance\"})",
     "legendFormat": "Response queue size"
    }
   ]
  },
  {
   "title": "Распределение времени ответа API-вызовов, p99 (RequestMetrics)",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "quantile(0.99, rate(kafka_network_requestmetrics_responsesendtimems{quantile=\"0.99\", instance=~\"$instance\", request=~\"$request\"}[$__rate_interval])) by (request)",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Всего API-вызовов (RequestMetrics)",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_responsesendtimems_count{instance=~\"$instance\",request=~\"$request\"}[$__rate_interval])) by (request)",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Число ошибок API-вызовов (RequestMetrics)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_errors_total{instance=~\"$instance\",request=~\"$request\",error!=\"NONE\"}[$__rate_interval])) by (request)",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  { "title": "Leader election", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Leaders",
   "type": "graph",
   "description": "Disk reads",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_leadercount{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Bytes in/out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{instance=~\"$instance\",topic!=\"\"}[$__rate_interval])) by (instance) + sum(rate(kafka_server_brokertopicmetrics_bytesout_total{instance=~\"$instance\",topic!=\"\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Messages in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{instance=~\"$instance\",topic!=\"\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Replication bytes in/out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_replicationbytesin_total{instance=~\"$instance\"}[$__rate_interval])) by (instance) + sum(rate(kafka_server_brokertopicmetrics_replicationbytesin_total{instance=~\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Producer requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_totalproducerequests_total{instance=~\"$instance\",topic!=\"\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Network request errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_errors_total{instance=~\"$instance\",error!=\"NONE\"}[$__rate_interval])) by (instance, error, request) > 0",
     "legendFormat": "{{kubernetes_pod_name}} ({{error}}) [{{request}}]"
    }
   ]
  },
  {
   "title": "Local time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_localtimems{instance=~\"$instance\"}[$__rate_interval])) by (instance) >= 0",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Remote time (acks=all)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_remotetimems{instance=~\"$instance\"}[$__rate_interval])) by (instance) >= 0",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Response queue time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_responsequeuetimems{instance=~\"$instance\"}[$__rate_interval])) by (instance) >= 0",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Response send time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_responsesendtimems{instance=~\"$instance\"}[$__rate_interval])) by (instance) >= 0",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "Утилизация памяти JVM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 123 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Memory pool JVM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_max{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used{instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Время работы GC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}